### ISSUE TITLE
GA failure to deploy shiny app issue

### ISSUE THREAD

**Issue by AnneMTreasure** [DHCSSza/stakeholder_map#36]
GitHub Action working for weeks, suddenly failed to deploy Shiny app

**Comment by AnneMTreasure** [comment]
**Edited the update_shiny.yml an DESCRIPTION file**

- in `update_shiny.yml` switched to ubuntu server (`runs-on: ubuntu-latest`)
- in `update_shiny.yml`, edited the steps to use `r-lib/actions/setup-r-dependencies@v2`, which installs all package dependencies defined in the DESCRIPTION file
- see [https://github.com/r-lib/actions/tree/v2/setup-r-dependencies](https://github.com/r-lib/actions/tree/v2/setup-r-dependencies) 

```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
```

- in `update_shiny.yml`, deleted all the `install.packages` script and added these packages to the DESCRIPTION file
- included the package `terra` to the DESCRIPTION file - the GitHub Action error logs showed this package to be needed, but not installing
- added `library(terra)` to the shiny `app.R`
